service=whostmgr
name=megastats
user=root
url=/cgi/megastats/index.cgi
url2=/cgi/addon_megastats.cgi
entryurl=megastats/index.cgi
displayname=MegaStats
description=Server monitoring dashboard (CPU, RAM, network, clients)
target=_self
acls=all
icon=megastats.png
searchtext=MegaStats monitoring server stats CPU RAM network clients
