service=cpaneld
name=megastats_mail
user=user
url=/3rdparty/megastats/mail.cgi
displayname=MegaStats Mail
description=Réputation email et blacklist de votre IP
target=_self
icon=megastats.png
searchtext=MegaStats mail blacklist RBL réputation IP
